Environment-specific PactBrokerUserPassword parameter
LBHackney-IT/person-api pull request #137
Opened 2022-02-16 16:17 UTC by vkapenkin

Made SSM parameter for Pact Broker password environment-specific to configure it on staging

2022-02-16 16:26 UTC, humulla approved these changes

2022-02-16 16:27 UTC, humulla requested changes
The pipeline is currently failing

2022-02-21 17:51 UTC, vkapenkin commented
Pipeline is fixed with updated Pact Broker certificate

2022-02-22 08:53 UTC, humulla approved these changes

2022-02-22 08:55 UTC, merged